### ISSUE TITLE
Create collection if its in appwrite.json

### ISSUE THREAD

**Issue by SEED-Foundation** [react-declarative/appwrite-backup-tool#2]
I there a way to create collections also ? not just documents ? .

**Comment by tripolskypetr** [comment]
Yeap, It is. Just run `npm run appwrite:create-collection`. Do not forget to change collection id in [scripts/create-collection.mjs#27](https://github.com/react-declarative/appwrite-backup-tool/blob/6604748563cb602de53283a45d4643e637cfea6f/scripts/create-collection.mjs#L27)
