### ISSUE TITLE
Hit into 'document_invalid_structure' during restore

### ISSUE THREAD

**Issue by maverickLDR** [react-declarative/appwrite-backup-tool#3]
Everything seems OK during the backup but halfway through the restore, I got hit with the following error:
```
Uploading 65cf00a8911df1be18f4 from 64e34922801293c026d6 from 64de1abab7f90a83e486
/mnt/c/repo/appwrite-backup/node_modules/node-appwrite/lib/client.js:174
                        throw new AppwriteException(error.response.data.message, error.response.status, error.response.data.type, error.response.data);
                              ^

AppwriteException [Error]: Invalid document structure: Unknown attribute: "$databaseId"
    at Client.call (/mnt/c/repo/appwrite-backup/node_modules/node-appwrite/lib/client.js:174:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Databases.createDocument (/mnt/c/repo/appwrite-backup/node_modules/node-appwrite/lib/services/databases.js:1691:16)
    at async file:///mnt/c/repo/appwrite-backup/scripts/restore.mjs:113:7 {
  code: 400,
  type: 'document_invalid_structure',
  response: {
    message: 'Invalid document structure: Unknown attribute: "$databaseId"',
    code: 400,
    type: 'document_invalid_structure',
    version: '1.3.7'
  }
}

Node.js v18.16.0
```

On the Appwrite server side, the server complained:
```
[Error] Timestamp: 2024-03-16T14:38:17+00:00
[Error] Method: POST
[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents
[Error] Type: Appwrite\Extend\Exception
[Error] Message: Invalid document structure: Unknown attribute: "$databaseId"
[Error] File: /usr/src/code/app/controllers/api/databases.php
[Error] Line: 2805
```

I am trying to recover from the following error: https://discordapp.com/channels/564160730845151244/1135229740903575633/1171178566591979563

using this tool.  Any help or tip would be very much appreciated!!!

**Comment by tripolskypetr** [comment]
Hey! Sounds like your collection schema is damaged. The first think you gonna try is to wrap [these lines](https://github.com/react-declarative/appwrite-backup-tool/blob/8caf2e69b4967ca3bcca8057fbe0e0a3b91f389d/scripts/restore.mjs#L113) with try-catch. If the only one document is broken this would help

```
try {
 await databases.createDocument(
    $databaseId,
    $collectionId,
    $id,
    writeTransform(data, $collectionId)
  );
} catch (error) {
  console.log(error);
}
```

If this won't help, please attach zip archive with backup folder

**Comment by tripolskypetr** [comment]
I recommend manually check the backup folder and if the data is actual, drop appwrite and recreate everything again. Better to deploy a copy to another appwrite cloud account without touching broken instance

P.S. If $databaseId only is missing, patch documents manually

**Comment by tripolskypetr** [comment]
Better not to use appwrite relations cause you just hit data loss. Separate documents are faster and able to be restored

https://www.wix.engineering/post/scaling-to-100m-mysql-is-a-better-nosql

**Comment by maverickLDR** [comment]
Thank you very much for the quick response.  Are you saying we shouldn't be using Appwrite BTW...?  From the previous post...
I wanted to write the very same thing that you have just done; have a way to export all the data and then re-insert into Appwrite using Appwrite's own tools but you have done a far better than I ever could have so I thank you from the bottom of my heart.

I will investigate the error - hopefully a simple data patch would fix it.

**Comment by maverickLDR** [comment]
BTW, is there a way to selectively restore a particular collection or even a particular document?

**Comment by tripolskypetr** [comment]
1. In our production we are using Appwrite **without** [relationships](https://appwrite.io/docs/products/databases/relationships). Each subquery can be done with AsynIterator API in nodejs or chrome without joining data on a db side. It serverless, It scaling. Much easier to backup/restore

```tsx
const listDocuments = async function* () {
  for await (const rows of iterateDocuments<IApartmentRow>({
    totalDocuments: 10_000,
    limit: 5_000,
    createRequest: async ({ lastId, limit }) => {
      const { documents } = await ioc.appwriteService.databases.listDocuments(
        CC_APPWRITE_CONFIG.databaseId,
        CC_APARTMENT_COLLECTION_ID,
        [
          Query.orderDesc("$updatedAt"),
          ...(lastId ? [Query.cursorAfter(lastId as string)] : []),
          Query.select([
            "$id",
            ...
          ]),
          Query.equal("is_removed", false),
          ...
          Query.limit(limit),
        ],
      );
      return listTransform<IApartmentRow>(documents);
    },
  })) {
    // The place for chunk subquery, you can list documents again with `Query.equal("$id", rows.map(({ $id }) => $id))`
    for (const row of rows) {
      yield row;
    }
  }
};

export const listApartment = async function* (data: IFilterData) {
  for await (const row of listDocuments()) {
    if (first(data.deal_side) === "sell" && !row.is_sell) {
      continue;
    }
    if (first(data.deal_side) === "rent" && !row.is_rent) {
      continue;
    }
    ...
    yield row;
  }
};
```

2. Ofc, that exactly what this tool does. It help you manage data in unix style. Just `rm -rf` some collections id `backup` folder and restore them: only existing documents in folder will be updated

@maverickLDR
