### ISSUE TITLE
Restore appwrite.json path

### ISSUE THREAD

**Issue by SafakB** [react-declarative/appwrite-backup-tool#8]
I got an error. I realised the error was related to the schematic file path. That's how I fixed it.

Os : Windows
Command : npm run appwrite:restore
Related File : restore.msj
Line : 12

```javascript
const schema = require(path.join(process.cwd(), "./appwrite.json"));
```

to
```javascript
const schema = require(path.join(process.cwd(), "./schema/appwrite.json"));
```

**Comment by tripolskypetr** [comment]
Why don't you simple copy appwrite.json to the root?

**Comment by SafakB** [comment]
Yes I can do that, but the fetch command places it in this folder


***appwrite_fetch.bat***
```
@echo off
if exist .\schema rmdir .\schema /s /q
mkdir .\schema
cd .\schema
```
